apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todoapp.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secretKey | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
