apiVersion: v1
kind: Service
metadata:
  name: {{ include "todoapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "todoapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
